Add Lef parser
eclufsc/openeda pull request #34
Opened 2016-09-23 14:36 UTC by thiagobbt

This closes #16

2016-09-23 18:08 UTC, renannetto reviewed
I suggest using the same interface used for VerilogParser:

Verilog \* readStream(std::istream & in);
Verilog \* readFile(const std::string & filename);

Which means the parser will read the lef file and return the pointer to the Lef object.

Besides that, some attributes and properties are not using the coding style, I guess this can be fixed using uncrustify.

2016-09-23 20:33 UTC, csguth requested changes

2016-09-23 20:33 UTC, csguth commented on .travis.yml
> +            - libboost-all-dev
Which version of boost is installed in this package?

2016-09-23 20:33 UTC, csguth commented on test/parser/lef_test.cpp
> +           // a.obses == b.obses &&
this line has no effect, please remove

2016-09-23 20:33 UTC, csguth commented on 3rdparty/LEF/.deps/lib_libLEF_la-crypt.Plo
> +3rd-party/LEF/lib_libLEF_la-crypt.lo: 3rd-party/LEF/crypt.cpp \
I think we could create a mirror repository for the Cadence's code, and add it as a submodule. It would be cleaner.

2016-09-23 20:43 UTC, thiagobbt commented on .travis.yml
> +            - libboost-all-dev
It should be the version present in Ubuntu Trusty(as configured by the dist directive in line 4) repositories, which is 1.54.0.1

2016-09-23 21:16 UTC, thiagobbt commented on test/parser/lef_test.cpp
> +           // a.obses == b.obses &&
Removed in 89044ce380d1ce08cd18ef7817f7bac8193d2356

2016-09-23 21:20 UTC, thiagobbt commented
@renannetto I implemented readFile in the class LefParser and fixed the style errors not covered by uncrustify. readStream wasn't implemented as lefrRead from the 3rd party library requires a filename.

2016-09-23 22:47 UTC, thiagobbt commented on 3rdparty/LEF/.deps/lib_libLEF_la-crypt.Plo
> +3rd-party/LEF/lib_libLEF_la-crypt.lo: 3rd-party/LEF/crypt.cpp \
Done!

2016-09-25 02:35 UTC, csguth commented on ophidian/parser/Lef.h
> +#include <LEF/include/lefrReader.hpp>
This can be moved to .cpp.
Hide dependency through PIMPL.

2016-09-25 02:36 UTC, csguth commented on ophidian/parser/Lef.h
> +	LefDefParser::lefiUnits m_units;
You can hide this with PIMPL.

2016-09-25 02:39 UTC, csguth commented on ophidian/parser/Lef.h
> +	LefDefParser::lefiUnits m_units;
`struct Impl;`
`std::unique_ptr<Impl> this_;`

In Lef.cpp:
`struct Lef::Impl {
LefDefParser::lefiUnits units_;
};`
`Lef::Lef() : this_(new Impl){}`
`double Lef::databaseUnits() const {
    return this_->m_units.databaseNumber();
}
`

2016-09-25 02:40 UTC, csguth commented on test/parser/lef_test.cpp
> +        // TODO: Check macro obses
??

2016-09-25 02:43 UTC, csguth requested changes
nice work!!

2016-09-25 03:11 UTC, thiagobbt commented on test/parser/lef_test.cpp
> +        // TODO: Check macro obses
As simple.lef doesn't have any elements in the layer2rects map I felt like it should be tested with another file that has them.

2016-09-25 23:53 UTC, csguth commented on test/parser/lef_test.cpp
> +        // TODO: Check macro obses
you can use superblue18's .lef.

2016-09-28 21:53 UTC, csguth approved these changes

2016-09-28 21:58 UTC, csguth requested changes

2016-09-28 21:58 UTC, csguth commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fext-numeric-literals")
what's this? it doesn't work on `clang`.

2016-09-28 23:32 UTC, csguth requested changes

2016-09-28 23:32 UTC, csguth commented on ophidian/parser/Lef.cpp
> +Lef* LefParser::readFile(const std::string &filename) {
switch to `std::shared_ptr<Lef>` and `return std::make_shared<Lef>(filename);`

2016-09-29 00:57 UTC, csguth requested changes

2016-09-29 00:57 UTC, csguth commented on ophidian/parser/Lef.cpp
> +{
please, move this logic to LefParser

2016-10-06 23:00 UTC, csguth requested changes

2016-10-06 23:00 UTC, csguth commented on .travis.yml
> +            - libboost-all-dev
I think it is not necessary anymore.

2016-10-06 23:00 UTC, csguth commented on ophidian/parser/Lef.h
> +    std::shared_ptr<Lef> readFile(const std::string & filename);
Please, switch to `std::unique_ptr<Lef>`

2016-10-16 23:37 UTC, csguth requested changes

2016-10-16 23:37 UTC, csguth commented on ophidian/parser/Lef.cpp
> +		throw "File could not be opened";
Leak!!

Remember to `std::fclose(fp)`. I suggest you to use a `std::unique_ptr<std::FILE>` with a custom deleter.

read: http://stackoverflow.com/questions/26360916/using-custom-deleter-with-unique-ptr

2016-10-20 00:22 UTC, csguth commented on ophidian/parser/CMakeLists.txt
> -install(FILES VerilogParser.h DESTINATION include/ophidian/parser)
freaking space

2016-10-20 00:22 UTC, csguth commented on ophidian/parser/Lef.cpp
> +	auto fp = std::unique_ptr<FILE, decltype(&std::fclose)>(std::fopen(filename.c_str(), "r"), &std::fclose);
nice!!

2016-10-20 00:22 UTC, csguth commented on ophidian/parser/Lef.cpp
> +	auto fp = std::unique_ptr<FILE, decltype(&std::fclose)>(std::fopen(filename.c_str(), "r"), &std::fclose);
Nice!!

2016-10-22 22:25 UTC, csguth approved these changes

2016-10-22 22:30 UTC, merged