Geometry
eclufsc/openeda pull request #36
Opened 2016-09-25 21:08 UTC by renannetto

This adds a Geometry module to ophidian. The geometry module contains models for points, segments, linestrings, boxes, polygons and multi polygons. It also defines distance metrics and operations such as translation, scaling, rotation and intersection. I also changed the .travis.yml file to install boost 1.59, since it is required to compile this module.

2016-09-25 23:38 UTC, csguth commented on test/geometry/intersectiontest.cpp
> +    //intersection(polygon1, polygon2, intersection);
?

2016-09-25 23:52 UTC, csguth requested changes

2016-09-26 00:41 UTC, renannetto commented on test/geometry/intersectiontest.cpp
> +    //intersection(polygon1, polygon2, intersection);
I actually forgot to fix this ;p
I will do that and update the request

2016-09-27 12:52 UTC, renannetto commented on test/geometry/intersectiontest.cpp
> +    //intersection(polygon1, polygon2, intersection);
fixed!

2016-09-27 16:25 UTC, csguth approved these changes

2016-09-27 16:25 UTC, merged