Parser exception
eclufsc/openeda pull request #41
Opened 2016-09-29 20:15 UTC by tarberd

2016-09-29 20:27 UTC, renannetto reviewed
Is there an example using this?

2016-09-29 20:30 UTC, tarberd commented
@renannetto 
FILE* ifp = fopen(filename.c_str(), "r");
if(!ipf)

2016-09-29 20:31 UTC, tarberd commented
@renannetto 
FILE* ifp = fopen(filename.c_str(), "r");
if(!ifp){ throw InexistentFile(); }

2016-09-29 20:55 UTC, csguth requested changes

2016-09-29 20:55 UTC, csguth commented on ophidian/parser/ParserException.h
> +
`#include <exception>`

2016-09-29 20:55 UTC, csguth commented on ophidian/parser/ParserException.h
> +        class InexistentFile {
`class InexistentFile : public std::exception { `

2016-09-29 20:55 UTC, csguth commented on ophidian/parser/ParserException.h
> +            std::string errorMessage(){
```
const char* what() const override {
   return "The given file was not found";
}
```

2016-09-29 21:07 UTC, tarberd commented
@csguth now it's following the standards ;)

2016-09-29 22:30 UTC, csguth requested changes

2016-09-29 22:30 UTC, csguth commented on ophidian/parser/ParserException.h
> +            const char* what() override {
please, make it public

2016-09-29 23:37 UTC, renannetto commented
can you also add a test that throws this exception when parsing an invalid file?

2016-10-11 16:06 UTC, csguth commented
@tarberd Pease, update this branch. Otherwise I can't merge it.

2016-10-16 23:32 UTC, csguth approved these changes

2016-10-16 23:33 UTC, merged