Feature/#20 liberty parser
eclufsc/openeda pull request #55
Opened 2017-02-15 01:42 UTC by TiagoAFontana

This adds liberty parser and removes clang from travis.

2017-02-15 18:47 UTC, csguth requested changes

2017-02-15 18:47 UTC, csguth commented on .travis.yml
> +  - make -j 1
`make -j 1` is the same as just `make`, isn't it?

2017-02-15 18:47 UTC, csguth commented on CMakeLists.txt
> +ExternalProject_Add(
This is not necessary for this PR.

2017-02-15 18:47 UTC, csguth commented on CMakeLists.txt
> +ExternalProject_Add(
Nevermind.

2017-02-15 18:47 UTC, csguth commented on CMakeLists.txt
> -	lef_parser
Please, avoid swapping lines. This makes the diff harder to understand.

2017-02-15 18:47 UTC, csguth commented on ophidian/parser/CMakeLists.txt
> +#LINK_DIRECTORIES(${THIRD_PARTY_BUILD_PATH}/libertyParser/lib/ )
Commented lines are useless. Please, remove.

2017-02-15 18:47 UTC, csguth commented on ophidian/parser/LibertyParser.cpp
> +
Blank lines.

2017-02-15 18:47 UTC, csguth commented on ophidian/parser/LibertyParser.cpp
> +        values.push_back(std::stod(segment));
Please, enclose with brackets.
```C++
while(cond)
{
    ...
}

2017-02-15 18:47 UTC, csguth commented on ophidian/parser/LibertyParser.cpp
> +//    std::vector< double > loadValues(8);
Please, remove commented lines.

2017-02-15 18:47 UTC, csguth commented on test/input_files/input_files
> +/home/tiago/devel/ophidian/test/input_files
Please remove this symlink.

2017-03-05 11:18 UTC, csguth commented
Please, create a PR just for the travis change.

2017-05-15 14:30 UTC, TiagoAFontana commented on test/input_files/input_files
> +/home/tiago/devel/ophidian/test/input_files
Ok. Removed. :)

2018-03-21 16:49 UTC, closed without merging